import Head from "next/head";
import Image from "next/image";
import { Jost } from "next/font/google";
import { Container, Row, Col, Card, Button } from "react-bootstrap";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import styles from "@/styles/Home.module.css";
import location1 from '../Images/locations/1.png'
import location2 from '../Images/locations/2.png'
import location3 from '../Images/locations/3.png'
import location4 from '../Images/locations/4.png'
import company1 from '../Images/company/1.png'
import company2 from '../Images/company/2.png'
import company3 from '../Images/company/3.png'
import company4 from '../Images/company/4.png'
import company5 from '../Images/company/5.png'
import d1 from '../Images/d1.svg'
import d2 from '../Images/d2.svg'
import d3 from '../Images/d3.svg'
import testimonial from '../Images/testimonial.png'
import person1 from '../Images/person1.jpg'
import Link from "next/link";
import Newsletter from "./components/common/Newsletter";
import CarCard from "./components/common/CarCard";
import { BsShieldFillCheck } from "react-icons/bs";
import Popularlocations from './components/common/PopularLocations'
// Define Jost font
const jostFont = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});
const sliderSettings = {
  dots: false,
  infinite: true,
  speed: 500,
  slidesToShow: 5,
  slidesToScroll: 1,
  margin: 30,
  arrows: true,
  prevArrow: <div className="prev-arrow">Prev</div>,
  nextArrow: <div className="next-arrow">Next</div>,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 4,
        slidesToScroll: 1,
      },
    },
    {
      breakpoint: 768,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 1,
      },
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
      },
    },
  ],
};  

const settings = {
  dots: false,
  infinite: true,
  speed: 500,
  slidesToShow: 1,
  slidesToScroll: 1,
  nextArrow: <button className={styles.nextArrow}>Next</button>,
  prevArrow: <button className={styles.prevArrow}>Prev</button>,
};

const locations = [
  { name: 'Location 1', image: location1 },
  { name: 'Location 2', image: location2 },
  { name: 'Location 3', image: location3 },
  { name: 'Location 4', image: location4 },
];

const cars = [
  {
    id: "1",
    name: "Tesla",
    rating: 5,
    reviews: 242,
    location: "Wilora NT 0872, Australia",
    price: "$165,3",
    distance: "12 km",
    wishlist: "/static/wishlist.png",
  },
  {
    id: "2",
    name: "BMW",
    rating: 4.5,
    reviews: 128,
    location: undefined,
    price: "$120,0",
    distance: "8 km",
    wishlist: undefined,
  },
];

export default function Home() {
  const testimonials = [
    {
      name: 'John Doe',
      location: 'New York, USA',
      testimonial: 'We have a unique combination of talents motivated by ambitious goals and a can-do attitude. Our drive to develop excellent products is built on teamwork, passion, and giving team members full control over their work to succeed on their own. We want to create an environment where ideas can flourish.',
      image: person1,
    },
    {
      name: 'Jane Smith',
      location: 'London, UK',
      testimonial: 'Amazing experience! I highly recommend this service.',
      image: person1,
    },
  ];

  return (
    <>
      <Head>
        <title>Unibooker | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${jostFont.variable}`}>
        {/* Hero Section */}
        <div className={styles.hero_bg}>
          <Container>
            <Row>
              <Col md={12}>
                <Card className={styles.search_box}>
                  <Card.Body>
                    <form>
                      <Row>
                        <Col md={2}>
                          <div className="form-inputs mb-3">
                            <label htmlFor="city">City</label>
                            <select id="city" className="form-control">
                              <option value="bangalore">Bangalore</option>
                              <option value="mumbai">Mumbai</option>
                              <option value="delhi">Delhi</option>
                              <option value="pune">Pune</option>
                              <option value="chennai">Chennai</option>
                            </select>
                          </div>
                        </Col>
                        <Col md={4}>
                          <div className="form-inputs mb-3">
                            <label htmlFor="location">Location</label>
                            <input
                              id="location"
                              type="text"
                              className="form-control"
                              placeholder="Enter a location"
                            />
                          </div>
                        </Col>
                        <Col md={2}>
                          <div className="form-inputs mb-3">
                            <label htmlFor="startDate">Trip Starts</label>
                            <input id="startDate" type="datetime-local" className="form-control" />
                          </div>
                        </Col>
                        <Col md={2}>
                          <div className="form-inputs mb-3">
                            <label htmlFor="endDate">Trip Ends</label>
                            <input id="endDate" type="datetime-local" className="form-control" />
                          </div>
                        </Col>
                        <Col md={2}>
                          <Button className={styles.theme_btn} type="submit">
                            Search Car
                          </Button>
                        </Col>
                      </Row>
                    </form>
                  </Card.Body>
                </Card>
              </Col>
              <Col md={12} lg={6} xl={6} className="mt-5">
                <h1>Easy and Convenient Way of Car Booking in <span>UniBooker</span></h1>
                <p>Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat.</p>
              </Col>
            </Row>
            <div className={styles.carouselValue}>
              <div className={styles.carouselValueContainer}>
                <div className={styles.carouselValueSection}>
                  <div className={styles.carouselValueSectionIcon}>
                    <BsShieldFillCheck />
                  </div>
                  <div className={styles.carouselValueSectionContent}>
                    <h4>100%</h4>
                    <p>Hassle-free Secured Trip</p>
                  </div>
                </div>
                <div className={styles.carouselValueSection}>
                  <div className={styles.carouselValueSectionIcon}>
                    <BsShieldFillCheck />
                  </div>
                  <div className={styles.carouselValueSectionContent}>
                    <h4>25000+</h4>
                    <p>Quality cars available</p>
                  </div>
                </div>
                <div className={styles.carouselValueSection}>
                  <div className={styles.carouselValueSectionIcon}>
                    <BsShieldFillCheck />
                  </div>
                  <div className={styles.carouselValueSectionContent}>
                    <h4>Delivery</h4>
                    <p>Anywhere, Anytime</p>
                  </div>
                </div>
                <div className={styles.carouselValueSection}>
                  <div className={styles.carouselValueSectionIcon}>
                    <BsShieldFillCheck />
                  </div>
                  <div className={styles.carouselValueSectionContent}>
                    <h4>Endless</h4>
                    <p>Drives, pay by hour</p>
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </div>
        <main className={`${styles.main} container`}>
          {/* Popular Locations Section */}
          <section className={styles.popular_locations}>
            <h2 className={styles.main_heading}>Popular Locations</h2>
            <Popularlocations
              locations={locations}
              sliderSettings={sliderSettings}
              variant="slider" // GRID FOR GRIDS
            />
            <Link className={styles.btn_link} href="/">Explore All</Link>
          </section>
          {/* Company Logos Section */}
          <section className={styles.company_logos}>
            <div className={styles.company_logos_row}>
              {/* {companyLogos.map((logo, index) => (
              <Col md={2} key={index}>
                <div className={styles.company_logos_div}>
                  <Image className={styles.locationImg} src={logo.src} alt={logo.alt} width={150} height={150} layout="intrinsic" />
                </div>
              </Col>
            ))} */}
              <div>
                <div className={styles.company_logos_div}>
                  <Image src={company1} alt="Company" />
                </div>
              </div>
              <div>
                <div className={styles.company_logos_div}>
                  <Image src={company2} alt="Company" />
                </div>
              </div>
              <div>
                <div className={styles.company_logos_div}>
                  <Image src={company3} alt="Company" />
                </div>
              </div>
              <div>
                <div className={styles.company_logos_div}>
                  <Image src={company4} alt="Company" />
                </div>
              </div>
              <div>
                <div className={styles.company_logos_div}>
                  <Image src={company5} alt="Company" />
                </div>
              </div>
            </div>
          </section>
          {/* Most Viewed Cars Section */}
          <section className={styles.most_viewed_cars}>
            <h2 className={styles.main_heading}>Most Viewed Cars</h2>
            <div className={styles.cars_row}>
              {cars.map((car) => (
                <Link key={car.id} href={`/cars/${car.id}`}>
                  <CarCard
                    id={car.id}
                    name={car.name}
                    rating={car.rating}
                    reviews={car.reviews}
                    location={car.location}
                    price={car.price}
                    distance={car.distance}
                    wishlist={car.wishlist}
                  />
                </Link>
              ))}
            </div>
            <Link className={styles.btn_link} href="/">Explore All</Link>
          </section>
          {/* Deliverables Section */}
          <section className={styles.deliverables}>
            <div className={styles.deliverables_row}>
              <div className={styles.deliverables_block}>
                <Image src={d1} alt="Deliverables" />
                <div className={styles.deliverables_content_block}>
                  <h5>700 Destinations</h5>
                  <p>Our expert team handpicked all destinations in this site</p>
                </div>
              </div>
              <div className={styles.deliverables_block}>
                <Image src={d2} alt="Deliverables" />
                <div className={styles.deliverables_content_block}>
                  <h5>700 Destinations</h5>
                  <p>Our expert team handpicked all destinations in this site</p>
                </div>
              </div>
              <div className={styles.deliverables_block}>
                <Image src={d3} alt="Deliverables" />
                <div className={styles.deliverables_content_block}>
                  <h5>700 Destinations</h5>
                  <p>Our expert team handpicked all destinations in this site</p>
                </div>
              </div>
            </div>
          </section>
          {/* Short Advertising Banner */}
          <section className={styles.advertising_banner}>
            <div className={styles.advertising_banner_content}>
              <h3>Lend your car to make <br /> some extra cash</h3>
              <Link className={styles.advertising_btn} href="/">Become A Host</Link>
            </div>
          </section>
          {/* Recommended Cars Section */}
          <section className={styles.recommended_cars}>
            <h2 className={styles.main_heading}>Recommended Cars</h2>
            <div className={styles.cars_row}>
              {cars.map((car) => (
                <Link
                  key={car.id}
                  href={{
                    pathname: `/cars/${car.id}`,
                    query: { car: JSON.stringify(car) }
                  }}
                >
                  <CarCard
                    id={car.id}
                    name={car.name}
                    rating={car.rating}
                    reviews={car.reviews}
                    location={car.location}
                    price={car.price}
                    distance={car.distance}
                    wishlist={car.wishlist}
                  />
                </Link>
              ))}
            </div>
          </section>
          {/* Travel Stories Section */}
          <section className={styles.travel_stories}>
            <h3>Client Testimonial</h3>
            <Row className="align-items-baseline">
              <Col md={6}>
                <Image src={testimonial} className={`${styles.travel_stories_img} img-fluid`} alt="Travel Story" />
              </Col>
              <Col md={6}>
                <div>
                  <Slider {...settings}>
                    {testimonials.map((testimonial, index) => (
                      <div key={index} className={styles.testimonialSlide}>
                        <p>{testimonial.testimonial}</p>
                        <div className={`${styles.testimonialUser} d-flex gap-3`}>
                          <Image src={testimonial.image} className={styles.testimonial_img} alt={`Testimonial from ${testimonial.name}`} />
                          <div className={styles.clientInfo}>
                            <h5>{testimonial.name}</h5>
                            <p>{testimonial.location}</p>
                          </div>
                        </div>
                      </div>
                    ))}
                  </Slider>
                </div>
              </Col>
            </Row>
          </section>
        </main>
        <Newsletter />
      </div>
    </>
  );
}