import Head from 'next/head'
import React from 'react'
import styles from "@/styles/CarList.module.css";
import { Col, Container, Row } from 'react-bootstrap';
import CarCard from '../components/common/CarCard';
import { Jost } from 'next/font/google';
import Link from 'next/link';
const jostFont = Jost({
    variable: "--font-jost",
    subsets: ["latin"],
});
const cars = [
    {
        id: "1",
        name: "Tesla",
        rating: 5,
        reviews: 242,
        location: "Wilora NT 0872, Australia",
        price: "$165,3",
        distance: "12 km",
        wishlist: "/static/wishlist.png",
    },
    {
        id: "2",
        name: "BMW",
        rating: 4.5,
        reviews: 128,
        location: undefined,
        price: "$120,0",
        distance: "8 km",
        wishlist: undefined,
    },
    {
        id: "3",
        name: "BMW",
        rating: 4.5,
        reviews: 128,
        location: undefined,
        price: "$120,0",
        distance: "8 km",
        wishlist: undefined,
    },
    {
        // image: "/images/car2.png",
        id: "4",
        name: "BMW",
        rating: 4.5,
        reviews: 128,
        location: undefined,
        price: "$120,0",
        distance: "8 km",
        wishlist: undefined,
    },
    {
        // image: "/images/car2.png",
        id: "5",
        name: "BMW",
        rating: 4.5,
        reviews: 128,
        location: undefined,
        price: "$120,0",
        distance: "8 km",
        wishlist: undefined,
    },
    {
        // image: "/images/car2.png",
        id: "6",
        name: "BMW",
        rating: 4.5,
        reviews: 128,
        location: undefined,
        price: "$120,0",
        distance: "8 km",
        wishlist: undefined,
    },
    {
        // image: "/images/car2.png",
        id: "7",
        name: "BMW",
        rating: 4.5,
        reviews: 128,
        location: undefined,
        price: "$120,0",
        distance: "8 km",
        wishlist: undefined,
    },

];
const index = () => {
    return (
        <>
            <Head>
                <title>Unibooker | Car List</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={`${styles.car_list_main} ${styles.page} ${jostFont.variable}`}>
                <Container>
                    <Row>
                        <Col md={12} className={styles.main_heading}>
                            <h2>Car List</h2>
                        </Col>
                        <Col md={3}>
                            <div className={styles.filter_section}>
                                <h5>Categories</h5>
                                <ul>
                                    <li><input type="checkbox" /> Electric</li>
                                    <li><input type="checkbox" /> SUV</li>
                                    <li><input type="checkbox" /> Sedan</li>
                                    <li><input type="checkbox" /> Coupe</li>
                                </ul>
                                <div className={styles.checkbox}>
                                    <h5>Price Range</h5>
                                    <div>Range: $0 - $1000</div>
                                    <input type="range" min="0" max="1000" step="50" />
                                </div>
                                <h5>Brands</h5>
                                <ul>
                                    <li><input type="checkbox" /> Tesla</li>
                                    <li><input type="checkbox" /> BMW</li>
                                    <li><input type="checkbox" /> Mercedes</li>
                                    <li><input type="checkbox" /> Audi</li>
                                </ul>
                                <ul>
                                    <li><input type="checkbox" /> On Sale</li>
                                    <li><input type="checkbox" /> Out of Stock</li>
                                </ul>
                                <h5>Ratings</h5>
                                <ul>
                                    <li>⭐⭐⭐⭐⭐</li>
                                    <li>⭐⭐⭐⭐</li>
                                    <li>⭐⭐⭐</li>
                                    <li>⭐⭐</li>
                                    <li>⭐</li>
                                </ul>
                            </div>
                        </Col>
                        <Col md={9} className='text-center'>
                            <div className={styles.cars_row}>
                                {cars.map((car) => (
                                    <Link
                                        key={car.id}
                                        href={{
                                            pathname: `/cars/${car.id}`,
                                            query: { car: JSON.stringify(car) }
                                        }}
                                    >
                                        <CarCard
                                            id={car.id}
                                            name={car.name}
                                            rating={car.rating}
                                            reviews={car.reviews}
                                            location={car.location}
                                            price={car.price}
                                            distance={car.distance}
                                            wishlist={car.wishlist}
                                        />
                                    </Link>
                                ))}
                            </div>
                        </Col>
                    </Row>
                </Container>
            </section>
        </>
    )
}

export default index
